# Generated by Django 5.1.6 on 2026-06-22 05:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('secteur', models.CharField(choices=[('COMMERCE', 'Commerce / Distribution'), ('SERVICES', 'Services'), ('AGRICULTURE', 'Agriculture / Agroalimentaire'), ('ARTISANAT', 'Artisanat'), ('TECHNOLOGIE', 'Technologie / Digital'), ('TRANSPORT', 'Transport / Logistique'), ('IMMOBILIER', 'Immobilier / Construction'), ('SANTE', 'Santé'), ('EDUCATION', 'Éducation / Formation'), ('AUTRE', 'Autre')], max_length=50, verbose_name="Secteur d'activité")),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='Burkina Faso', max_length=100, verbose_name='Pays')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('est_active', models.BooleanField(default=True, verbose_name='Entreprise active')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('GERANT', 'Gérant'), ('COMMERCIAL', 'Commercial'), ('COMPTABLE', 'Comptable'), ('RESPONSABLE', 'Responsable'), ('AUTRE', 'Autre')], default='GERANT', max_length=20, verbose_name='Rôle')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('date_derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('onboarding_complete', models.BooleanField(default=False, verbose_name='Onboarding terminé')),
                ('onboarding_date', models.DateTimeField(blank=True, null=True, verbose_name="Date de l'onboarding")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs', to='core.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ProfilEntreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectif_court_terme', models.TextField(blank=True, max_length=500, verbose_name='Objectif court terme')),
                ('objectif_long_terme', models.TextField(blank=True, max_length=500, verbose_name='Objectif long terme')),
                ('services_prioritaires', models.JSONField(default=list, help_text="Liste des services dont l'entreprise a besoin en priorité", verbose_name='Services prioritaires')),
                ('description_activite', models.TextField(blank=True, max_length=1000, verbose_name="Description de l'activité")),
                ('nombre_employes', models.PositiveIntegerField(blank=True, null=True, verbose_name="Nombre d'employés")),
                ('chiffre_affaires_annuel', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name="Chiffre d'affaires annuel (FCFA)")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du profil')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('complet', models.BooleanField(default=False, verbose_name='Profil complet')),
                ('entreprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to='core.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Profil entreprise',
                'verbose_name_plural': 'Profils entreprise',
            },
        ),
    ]
