# Generated by Django 5.1.6 on 2026-06-22 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeMemoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu_resume', models.TextField(verbose_name='Contenu du résumé')),
                ('date_maj', models.DateTimeField(auto_now_add=True, verbose_name='Date de mise à jour')),
                ('dernier_sujet', models.CharField(blank=True, max_length=200, verbose_name='Dernier sujet abordé')),
                ('decisions_prises', models.JSONField(default=list, verbose_name='Décisions prises')),
                ('recommandations', models.JSONField(default=list, verbose_name='Recommandations')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memoires', to='core.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Résumé de mémoire',
                'verbose_name_plural': 'Résumés de mémoire',
                'ordering': ['-date_maj'],
            },
        ),
    ]
