# Generated by Django 5.1.6 on 2026-06-25 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_resumememoire'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnexionFacebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=100, unique=True, verbose_name='ID de la page')),
                ('page_nom', models.CharField(max_length=200, verbose_name='Nom de la page')),
                ('access_token', models.TextField(help_text='Token de page long terme', verbose_name="Token d'acces")),
                ('token_expire_le', models.DateTimeField(blank=True, null=True, verbose_name='Token expire le')),
                ('date_connexion', models.DateTimeField(auto_now_add=True, verbose_name='Date de connexion')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Derniere modification')),
                ('est_active', models.BooleanField(default=True, verbose_name='Connexion active')),
                ('entreprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connexion_facebook', to='core.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Connexion Facebook',
                'verbose_name_plural': 'Connexions Facebook',
            },
        ),
        migrations.CreateModel(
            name='PublicationProgrammee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=100, verbose_name='ID de la page Facebook')),
                ('page_nom', models.CharField(max_length=200, verbose_name='Nom de la page')),
                ('contenu_texte', models.TextField(verbose_name='Contenu du post')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name="URL de l'image")),
                ('image_fichier', models.ImageField(blank=True, null=True, upload_to='publications/', verbose_name='Image')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication prevue')),
                ('date_publication_reelle', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication reelle')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de publication'), ('PUBLIEE', 'Publiee'), ('ECHEC', 'Echec'), ('ANNULEE', 'Annulee')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('message_erreur', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de creation')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Derniere modification')),
                ('publication_id_facebook', models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Facebook')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='core.entreprise', verbose_name='Entreprise')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Publication programmee',
                'verbose_name_plural': 'Publications programmees',
                'ordering': ['-date_creation'],
            },
        ),
    ]
