# Generated by Django 5.1.6 on 2026-06-25 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        ('core', '0002_resumememoire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationprogrammee',
            name='image_fichier',
        ),
        migrations.RemoveField(
            model_name='publicationprogrammee',
            name='image_url',
        ),
        migrations.CreateModel(
            name='ConfigurationFacebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(blank=True, max_length=100, null=True, verbose_name="ID de l'application Facebook")),
                ('app_secret', models.CharField(blank=True, max_length=200, null=True, verbose_name="Clé secrète de l'application")),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('entreprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config_facebook', to='core.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Configuration Facebook',
                'verbose_name_plural': 'Configurations Facebook',
            },
        ),
    ]
