# Generated by Django 5.1.6 on 2026-06-25 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0002_remove_publicationprogrammee_image_fichier_and_more'),
        ('core', '0002_resumememoire'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connexionfacebook',
            unique_together={('entreprise', 'page_id')},
        ),
        migrations.AlterField(
            model_name='connexionfacebook',
            name='access_token',
            field=models.TextField(verbose_name="Token d'acces Facebook"),
        ),
        migrations.AlterField(
            model_name='connexionfacebook',
            name='page_id',
            field=models.CharField(max_length=100, verbose_name='ID de la page Facebook'),
        ),
        migrations.AlterField(
            model_name='connexionfacebook',
            name='page_nom',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nom de la page'),
        ),
        migrations.DeleteModel(
            name='ConfigurationFacebook',
        ),
        migrations.RemoveField(
            model_name='connexionfacebook',
            name='token_expire_le',
        ),
    ]
