# Generated by Django 5.1.6 on 2026-06-22 18:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('segment', models.CharField(choices=[('PREMIUM', 'Premium'), ('STANDARD', 'Standard'), ('BASIQUE', 'Basique')], default='STANDARD', max_length=20, verbose_name='Segment')),
                ('score_rfm', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Score RFM')),
                ('date_premier_achat', models.DateField(blank=True, null=True, verbose_name='Date du premier achat')),
                ('date_dernier_achat', models.DateField(blank=True, null=True, verbose_name='Date du dernier achat')),
                ('nombre_achats', models.PositiveIntegerField(default=0, verbose_name="Nombre d'achats")),
                ('montant_total_achats', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='Montant total des achats (FCFA)')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Client actif')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='core.entreprise', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['-montant_total_achats'],
                'unique_together': {('entreprise', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('APPEL', 'Appel téléphonique'), ('EMAIL', 'Email'), ('RENCONTRE', 'Rencontre physique'), ('WHATSAPP', 'WhatsApp'), ('AUTRE', 'Autre')], max_length=20, verbose_name="Type d'interaction")),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'interaction")),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('suivi', models.BooleanField(default=False, verbose_name='Suivi nécessaire')),
                ('date_suivi', models.DateTimeField(blank=True, null=True, verbose_name='Date de suivi')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='crm.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
                'ordering': ['-date'],
            },
        ),
    ]
