# Generated by Django 5.1.6 on 2026-06-22 18:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='donnees',
            field=models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priorite',
            field=models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('CRITIQUE', 'Critique')], default='MOYENNE', max_length=20, verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('INFO', 'Information'), ('SUCCES', 'Succès'), ('ALERTE', 'Alerte'), ('EMAIL', 'Email'), ('RECOMMANDATION', 'Recommandation'), ('URGENT', 'Urgent')], default='INFO', max_length=20, verbose_name='Type'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['utilisateur', 'est_lue'], name='notificatio_utilisa_1dafee_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['date_creation'], name='notificatio_date_cr_1b0271_idx'),
        ),
    ]
